### ISSUE TITLE
Relicense Request

### ISSUE THREAD

**Issue by ddrinka** [sambott/PortableWikiViewer#3]
@sambott would you be up for re-licensing this code with an MIT license?  I'd love to use it but GPL won't fit with the rest of the project.  As a comparison point, sharpcompress, which I think you'd like to have this code integrated with, uses the MIT license.

**Comment by sambott** [comment]
Hi. No problem, will do. Glad you are getting some use out of it, what are you using it for?

**Comment by ddrinka** [comment]
I've got a bunch of pcap data collected off a remote sensor I've stored in S3, compressed with XZ.  I'm streaming it down, decompressing it, reassembling it, and processing it.  I'm currently using ManagedXZ but I'm looking for an _actual_ managed-only solution so I can move my batch process to a docker instance running on Linux later on.

**Comment by sambott** [comment]
Nice. I'm a bit snowed under at the moment, probably won't get around to this for a week or so. If you're wanting to use this now I can add you as a contributor here and on NuGet so you can get going straight away and publish it, if you like?

(If you want Nuget.org too, let me know your handle)

**Comment by ddrinka** [comment]
@sambott Don't worry about any of that.  As long as you're up for licensing with the MIT license I can keep hacking away in my fork.  It'll be a while before I have any code to contribute back anyhow.

Thanks for your help!

**Comment by adamhathcock** [comment]
I would like to have this as part of sharpcompress.  MIT would be ideal.

**Comment by sambott** [comment]
Relicensed in 1c60f3ffae995bd82cad11d699162dfc476a39c9
